name: Check

on:
  # Run on pushes to main..
  push:
    branches:
      - main
  # ..and any pull request.
  pull_request:

jobs:
  vulnerability:
    name: Vulnerability
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - run: yarn
      - run: yarn build --ignore docs
      - run: ./scripts/ci_check_vulnerabilities.sh
      - run: |
          mkdir -p test-results/jest
          yarn run lerna --ignore @celo/mobile run test
      - name: 'Upload Test Results'
        uses: actions/upload-artifact@v2
        with:
          path: test-results
  general:
    name: General Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - run: yarn
      - run: yarn build --ignore docs
      - run: |
          mkdir -p test-results/jest
          yarn run lerna --ignore @celo/mobile run test
      - name: 'Upload Test Results'
        uses: actions/upload-artifact@v2
        with:
          path: test-results
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      # https://github.com/actions/cache/blob/main/examples.md#node---lerna
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn run prettify:diff
      - run: yarn run lint
  mobile-tests:
    name: Mobile Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - name: Install Yarn dependencies
        run: yarn
      - name: Build Yarn packages
        run: yarn build --ignore docs
      - name: Run mobile tests
        run: yarn --cwd packages/mobile test:ci --runInBand
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          path: packages/mobile/coverage/lcov-report
