name: E2E Wallet Fund and Faucet Balance
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'E2E Wallet Fund and Faucet Balance'
  # Cron job to run faucet fund and balance every 8th hour
  schedule:
    - cron: '0 */8 * * *'

jobs:
  balance-and-fund:
    name: balance-and-fund
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/yarn-install
      - name: Create E2E Fund .env File
        env:
          TEST_FAUCET_SECRET: ${{ secrets.TEST_FAUCET_SECRET }}
        working-directory: e2e
        run: echo TEST_FAUCET_SECRET=$TEST_FAUCET_SECRET >> .env
      - name: Run Balance and Fund
        run: NODE_OPTIONS='--unhandled-rejections=strict' yarn ts-node ./e2e/scripts/fund-e2e-accounts.ts
