name: Run E2E

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'End-to-end Tests'

jobs:
  ios:
    name: iOS Tests
    runs-on: ios-e2e-group
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - name: Install package dependencies
        run: yarn
      - name: Build mobile dependencies
        run: yarn build --scope @celo/mobile --include-filtered-dependencies
      - name: Install Ruby dependencies
        run: |
          cd packages/mobile
          bundle install
      - name: Install CocoaPods dependencies
        run: |
          cd packages/mobile/ios
          bundle exec pod install
      - name: Run E2E tests
        run: |
          cd packages/mobile
          yarn run detox build-framework-cache
          yarn run test:e2e:ios -w 2
      # Publish Test Results
      - name: Publish JUnit Report
        if: always()
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'packages/mobile/e2e/test-results/junit.xml'
      # Upload Artifacts
      - name: 'Upload E2E Artifacts'
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          path: packages/mobile/e2e/artifacts
      - name: 'Upload E2E HTML Report'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          path: packages/mobile/e2e/test-results
  android:
    name: Android Tests
    runs-on: android-e2e-group
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - name: Install package dependencies
        run: yarn
      - name: Build mobile dependencies
        run: yarn build --scope @celo/mobile --include-filtered-dependencies
      - name: Run E2E tests
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-tools
          export ANDROID_NDK=$ANDROID_SDK_ROOT/ndk/21.0.6113669
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest:$PATH
          export PATH=$ANDROID_SDK_ROOT/platform-tools:$PATH
          export PATH=$ANDROID_SDK_ROOT/emulator:$PATH
          cd packages/mobile
          yarn run test:e2e:android -w 1
