name: Verify Locales

on:
  push:
    branches:
      - 'l10n/**'
  pull_request:
      - 'l10n/**'

jobs:
  verify-locales:
    name: Verify Locales
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - name: Install Yarn dependencies
        run: yarn
      - name: Build Yarn packages
        run: yarn build --ignore docs
      - name: Verify locales
        run: |
          cd packages/mobile
          yarn --cwd packages/mobile test:verify-locales
